name: sci_web
description: Simple web component lib.
version: 1.0.0

environment:
  sdk: ^3.3.0

dependencies:
  codemirror:
  markdown:
  synchronized:
  sci_base:
    git:
      url: https://github.com/tercen/sci_base
      ref: 1.0.0
#  sci_base:
#    path:  ../sci_base

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
